<?php

/**
 * Conta
 * 
 * This class has been auto-generated by the Code Igniter Generator Framework
 * 
 */
class Atendimentos_model extends CI_Model
{
	public $table = "atendimentos";

	public function __construct()
	{
		parent::__construct();
	}
	
}
