<?php

/**
 * Conta
 * 
 * This class has been auto-generated by the Code Igniter Generator Framework
 * 
 */
class Especialidades_model extends CI_Model
{
	public $table = "especialidades";

	public function __construct()
	{
		parent::__construct();
	}

	public function getEspecialidades(){
		return $this->db->query("SELECT id, nome_espec, status
						  FROM especialidades 
						  ORDER BY nome_espec 
						  ASC")
					->result();
	}
	
}
