<?php

/**
 * Conta
 * 
 * This class has been auto-generated by the Code Igniter Generator Framework
 * 
 */
class HorariosProfissionais_model extends CI_Model
{
	public $table = "horarios_profissionais";

	public function __construct()
	{
		parent::__construct();
	}


	public function getHorariosProfissional($profissionais_id){

		return $this->db->query("	SELECT hp.id, hp.status, hp.createdAt, hp.horarios_id, h.desc_horario, ds.desc_dia_semana, p.nome_prof
									FROM horarios_profissionais as hp
									INNER JOIN (horarios as h, dias_semana as ds, profissionais as p)
									ON (hp.horarios_id = h.id AND hp.dias_semana_id = ds.id AND hp.profissionais_id = p.id)
									WHERE hp.profissionais_id = $profissionais_id AND hp.status = 1")
						->result();
	}
}
