<?php

/**
 * Conta
 * 
 * This class has been auto-generated by the Code Igniter Generator Framework
 * 
 */
class Horarios_model extends CI_Model
{
	public $table = "horarios";

	public function __construct()
	{
		parent::__construct();
	}

	public function getHorarios() {
		return $this->db->query(" SELECT * 
								  FROM horarios
								  ORDER BY desc_horario ASC")
						->result();
	}
	
}
