<?php

/**
 * Conta
 * 
 * This class has been auto-generated by the Code Igniter Generator Framework
 * 
 */
class ItemConsulta_model extends CI_Model
{
	public $table = "item_consulta";

	public function __construct()
	{
		parent::__construct();
	}

	public function setConstultaPorDia($value='') {
		return $this->db->query(" SELECT ic.id, h.desc_horario, h.id as horarios_id, ds.id as dia_semana_id, ds.desc_dia_semana, pc.data, ic.status, 		c.id as cod_consulta, c.valor, p.id as paciente_id, pr.id as profissional_id, e.id as especialidade_id,
								pl.id as plano_id , pp.id as plano_procedimento_id,
						      p.nome_pac, pr.nome_prof, e.nome_espec, pl.nome_plano, ic.periodo_consulta_id
						      FROM item_consulta as ic
						      INNER JOIN(horarios_profissionais as hp, horarios as h, dias_semana as ds,
						      periodo_consulta as pc, consultas as c,
						      pacientes as p, profissionais as pr,
						      especialidades as e, plano_procedimento as pp, planos as pl)
						      ON (ic.horarios_id = hp.id AND hp.horarios_id = h.id AND ic.dia_semana_id = ds.id AND ic.periodo_consulta_id = pc.id AND ic.consultas_id = c.id AND c.pacientes_id = p.id AND c.profissionais_id = pr.id AND pr.especialidades_id = e.id AND c.plano_procedimento_id = pp.id AND pp.planos_id = pl.id)
						      WHERE ic.periodo_consulta_id = $periodo_consulta_id  AND ic.id = $id
						      ")

						->result();
	}
	
}
