<?php

/**
 * Conta
 * 
 * This class has been auto-generated by the Code Igniter Generator Framework
 * 
 */
class Pacientes_model extends CI_Model
{
	public $table = "pacientes";

	public function __construct()
	{
		parent::__construct();
	}

	public function getPacientes(){

		return $this->db->query("SELECT id, nome_pac, email_pac, telefone_pac, status, createdAt, updatedAt
								FROM pacientes AS pp
								ORDER BY nome_pac ASC")
						->result();
	}
	
}
