<?php

/**
 * Conta
 * 
 * This class has been auto-generated by the Code Igniter Generator Framework
 * 
 */
class Permissoes_model extends CI_Model
{
	public $table = "permissoes";

	public function __construct()
	{
		parent::__construct();
	}


	public function getClasse(){
		return $this->db->query("SELECT id, classe, metodo 
						  FROM metodos 
						  ORDER BY metodo 
						  ASC")
					->result();
	}

	public function getUsuarios(){
		return $this->db->query("SELECT id, nome 
						  FROM usuarios 
						  ORDER BY nome 
						  ASC")
					->result();
	}

	//encontra a lista de controllers pelo id do usuário
	public function getClassesId($usuarioId){
		
		$query = "SELECT * FROM permissoes WHERE usuarios_id = '".$this->db->escape_str($usuarioId)."'";
		$result = $this->db->query($query);
		
		$listClasses = array();
		foreach($result->result() as $classe){
			$listClasses[] = $classe->metodos_id;
		}
		return $listClasses;
	}
}
