<?php

/**
 * Conta
 * 
 * This class has been auto-generated by the Code Igniter Generator Framework
 * 
 */
class Planos_model extends CI_Model
{
	public $table = "planos";

	public function __construct()
	{
		parent::__construct();
	}

	public function getPlanos() {
		return $this->db->query("SELECT id, nome_plano, telefone_plano, email_plano, status, createdAt, updatedAt
								 FROM planos
								 ORDER BY id DESC")
						->result();

	}

	public function getPlanosPorEspecialidade($especialidades_id) {
		return $this->db->query("   SELECT p.id, p.nome_plano
									FROM planos AS p
									INNER JOIN (plano_procedimento AS pp, especialidades AS e) 
									ON (pp.especialidades_id = e.id AND pp.planos_id = p.id)
									WHERE pp.especialidades_id = $especialidades_id
									ORDER BY id DESC")
						->result();

	}
	
}
