<?php

/**
 * Conta
 * 
 * This class has been auto-generated by the Code Igniter Generator Framework
 * 
 */
class PlanoProcedimento_model extends CI_Model
{
	public $table = "plano_procedimento";

	public function __construct()
	{
		parent::__construct();
	}
	
	public function getProcedimentoPorPlano(){

		return $this->db->query("SELECT pp.id, p.nome_plano, e.nome_espec, pp.valor, pp.status, pp.createdAt
								 FROM plano_procedimento AS pp
								 INNER JOIN (planos as p, especialidades as e)
								 ON (pp.planos_id = p.id AND pp.especialidades_id = e.id) 
								 WHERE pp.status = 1
								 ORDER BY p.nome_plano ASC, e.nome_espec ASC")
						->result();
	}
}
