<?php

/**
 * Conta
 * 
 * This class has been auto-generated by the Code Igniter Generator Framework
 * 
 */
class Profissionais_model extends CI_Model
{
	public $table = "profissionais";

	public function __construct()
	{
		parent::__construct();
	}

	public function getProfissionais(){
		return $this->db->query("SELECT id, nome_prof, status
						  FROM profissionais 
						  ORDER BY nome_prof 
						  ASC")
					->result();
	}

	public function getProfissionaisPorId($profissionais_id){
		return $this->db->query("SELECT id, nome_prof
						  FROM profissionais 
						  ORDER BY nome_prof 
						  ASC")
					->result();
	}

	public function getProfissionaisPorEspecialidade($especialidades_id){
		return $this->db->query("SELECT id, nome_prof, status
						  FROM profissionais
						  WHERE especialidades_id = $especialidades_id
						  ORDER BY nome_prof 
						  ASC")
					->result();
	}

	public function getProfissionaisPorConsulta(){
		return $this->db->query("SELECT p.id, p.nome_prof, p.status
						  FROM profissionais AS p
						  INNER JOIN consultas AS c
						  ON (c.profissionais_id = p.id)
						  GROUP BY p.id
						  ORDER BY nome_prof 
						  ASC")
					->result();
	}

	public function getProfissionaisPorPlanoProcedimento($plano_procedimento_id){
		return $this->db->query("SELECT pp.id, pp.especialidades_id, f.especialidades_id, f.id AS prof_id, f.nome_prof
									FROM plano_procedimento AS pp
								 INNER JOIN (profissionais as f)
								 ON (f.especialidades_id = pp.especialidades_id) 
								 WHERE pp.status = 1 AND pp.id = $plano_procedimento_id
						         ORDER BY f.nome_prof 
						         ASC")
					->result();
	}
	
}
